### ISSUE TITLE
arp-table.json error

### ISSUE THREAD

**Issue by edouardkleinhans** [sbender9/signalk-sonoff-ewelink#26]
Hello, the plugin is failing in lan mode. It can't create arp-table.json.

```
May 17 10:20:55 2024-05-17T08:20:55.844Z signalk-sonoff-ewelink found devices: [{"_id":"6645bbd642911f000813c317","family":{"room":{},"members":[],"id":"5ea1c961a873c1000761b8be","guests":[],"index":0},"extraNotify":{},"group":"","online":true,"groups":[],"devGroups":[],"relational":[],"deviceid":"1001e6bbc9","name":"Devicee6bbc9","type":"10","apikey":"ff3f8e81-15ea-4256-af0e-fbcb68a69bdc","extra":{"_id":"64086580b506e933790e6120","extra":{"uiid":141,"itCredential":"KyDfDX9dZrKPXOuc","brandId":"59e0dbc25c1af3a660cc1ac0","apmac":"d0:27:03:44:37:65","mac":"d0:27:03:44:37:64","ui":"四通道插座_支持2.4G轻智能","modelInfo":"61289f66468ef65e1a4b29e0","model":"CK-BL602-4SW-HS","manufacturer":"深圳酷宅科技有限公司"}},"settings":{"opsNotify":0,"opsHistory":1,"alarmNotify":1,"wxAlarmNotify":0,"wxOpsNotify":0,"wxDoorbellNotify":0,"appDoorbellNotify":1},"params":{"bindInfos":{},"version":8,"rssi":-47,"fwVersion":"1.4.1","switches":[{"switch":"on","outlet":0},{"switch":"off","outlet":1},{"switch":"on","outlet":2},{"switch":"on","outlet":3}],"configure":[{"startup":"off","outlet":0},{"startup":"off","outlet":1},{"startup":"off","outlet":2},{"startup":"off","outlet":3}],"pulses":[{"pulse":"off","switch":"off","outlet":0,"width":0},{"pulse":"off","switch":"off","outlet":1,"width":0},{"pulse":"off","switch":"off","outlet":2,"width":0},{"pulse":"off","switch":"off","outlet":3,"width":0}],"remoteCtrlList":[{"outlet":0,"addr":[]},{"outlet":1,"addr":[]},{"outlet":2,"addr":[]},{"outlet":3,"addr":[]}],"lightScenes_0":[],"lightScenes_1":[],"lightScenes_2":[],"lightScenes_3":[],"sledOnline":"on","ssid":"Tic-et-Tac","bssid":"c6:ad:34:31:21:e5","addr":"eabb7f86","only_device":{"ota":"success","ota_fail_reason":0}},"createdAt":"2024-05-16T07:55:02.046Z","shareUsersInfo":[],"__v":0,"address":"/82.67.35.146:51294","ip":"82.67.35.146","location":"","onlineTime":"2024-05-17T08:19:04.280Z","tags":{"m_9bdc_edou":"on"},"offlineTime":"2024-05-16T15:33:25.581Z","sharedTo":[],"devicekey":"c85909d0-d8ec-4123-a631-e4996e85058a","deviceUrl":"","brandName":"coolkit","showBrand":false,"brandLogoUrl":"","productModel":"CK-BL602-4SW-HS(141)","devConfig":{},"uiid":141}]
May 17 10:20:55 2024-05-17T08:20:55.849Z signalk-sonoff-ewelink sending meta: [{"path":"electrical.switches.devicee6Bbc9.0.state","value":{"displayName":"0","units":"bool","order":0}},{"path":"electrical.switches.devicee6Bbc9.0","value":{"displayName":"0","order":0}},{"path":"electrical.switches.devicee6Bbc9.1.state","value":{"displayName":"1","units":"bool","order":1}},{"path":"electrical.switches.devicee6Bbc9.1","value":{"displayName":"1","order":1}},{"path":"electrical.switches.devicee6Bbc9.2.state","value":{"displayName":"2","units":"bool","order":2}},{"path":"electrical.switches.devicee6Bbc9.2","value":{"displayName":"2","order":2}},{"path":"electrical.switches.devicee6Bbc9.3.state","value":{"displayName":"3","units":"bool","order":3}},{"path":"electrical.switches.devicee6Bbc9.3","value":{"displayName":"3","order":3}}]

May 17 10:20:55 2024-05-17T08:20:55.859Z signalk-sonoff-ewelink saving device cache...
May 17 10:20:56 signalk-sonoff-ewelink:Error: ENOENT: no such file or directory, open '/home/ekleinhans/.signalk/plugin-config-data/signalk-sonoff-ewelink/arp-table.json'
May 17 10:20:56 Error: ENOENT: no such file or directory, open '/home/ekleinhans/.signalk/plugin-config-data/signalk-sonoff-ewelink/arp-table.json' at Object.openSync (node:fs:596:3) at Object.readFileSync (node:fs:464:35) at readArpTabel (/home/ekleinhans/.signalk/node_modules/signalk-sonoff-ewelink/dist/index.js:990:30) at /home/ekleinhans/.signalk/node_modules/signalk-sonoff-ewelink/dist/index.js:386:25 at step (/home/ekleinhans/.signalk/node_modules/signalk-sonoff-ewelink/dist/index.js:58:23) at Object.next (/home/ekleinhans/.signalk/node_modules/signalk-sonoff-ewelink/dist/index.js:39:53) at fulfilled (/home/ekleinhans/.signalk/node_modules/signalk-sonoff-ewelink/dist/index.js:30:58) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
May 17 10:20:56 2024-05-17T08:20:56.300Z signalk-sonoff-ewelink starting dnsd browser...
May 17 10:20:56 Error: getaddrinfo -3008 at errnoException (/home/ekleinhans/.signalk/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11) at getaddrinfo_complete (/home/ekleinhans/.signalk/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10) at GetAddrInfoReqWrap.oncomplete (/home/ekleinhans/.signalk/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9) { code: -3008, errno: -3008, syscall: 'getaddrinfo' }
```

**Comment by sbender9** [comment]
that error is normal the first time the plugin starts.

do you keep getting it after restarting the server?
